name: build_run_test

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 Job triggered by ${{ github.event_name }} event."
      - run: |
          echo "🐧 Job running on a ${{ runner.os }} server hosted by GitHub!"
      - run: |
          echo "🔎 Branch: ${{ github.ref }}; repository: ${{ github.repository }}."
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'
      - name: Print out installed python version
        run: |
          python --version
      - name: Upgrade pip, setuptools, wheel
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Install required packages
        run: |
          pip install -r requirements.txt
      - name: Print out installed pip packages
        run: |
          pip freeze
      - name: Convert test notebook
        run: |
          jupyter nbconvert --execute --to html 01_test_notebook.ipynb
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: knutzk/ml-workshop:latest
