name: docker_image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: knutzk/ml-workshop:latest
      # - run: docker build -t jp-tf-nb .
      # - run: docker run --rm -u $(id -u):$(id -g) -P jp-tf-nb jupyter --version
      # - run: docker run --rm -u $(id -u):$(id -g) -P -v $PWD:/data jp-tf-nb jupyter nbconvert --execute --to html 01_test_notebook.ipynb
